'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
const W=360,H=640;
type Ob={x:number;y:number;w:number;h:number;speed:number;type:'car'|'barrier'|'cone'};
const rand=(a:number,b:number)=>Math.random()*(b-a)+a;
function rr(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){c.beginPath();c.roundRect(x,y,w,h,r)}
export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement>(null); const raf=useRef<number|null>(null); const g=useRef({running:false,score:0,best:0,last:0,spawn:0,px:180,tx:180,obs:[] as Ob[],speed:145});
 const [screen,setScreen]=useState<'start'|'game'|'over'>('start'); const [score,setScore]=useState(0); const [best,setBest]=useState(0);
 useEffect(()=>{const b=Number(localStorage.getItem('street-best')||0);g.current.best=b;setBest(b)},[]);
 const end=useCallback(()=>{const x=Math.floor(g.current.score);g.current.running=false;if(x>g.current.best){g.current.best=x;setBest(x);localStorage.setItem('street-best',String(x))}setScreen('over')},[]);
 const start=useCallback(()=>{Object.assign(g.current,{running:true,score:0,last:performance.now(),spawn:0,px:180,tx:180,obs:[],speed:145});setScore(0);setScreen('game')},[]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const draw=(now:number)=>{const q=g.current,dt=Math.min((now-q.last)/1000||0,.033);q.last=now;if(q.running){q.score+=dt*10;q.speed+=dt*2.4;q.spawn-=dt;q.px+=(q.tx-q.px)*Math.min(1,dt*12);if(q.spawn<=0){const t=Math.random()<.58?'car':Math.random()<.72?'barrier':'cone';const w=t==='car'?52:t==='barrier'?76:34,h=t==='car'?92:t==='barrier'?30:38;q.obs.push({x:rand(42,W-42-w),y:-h-20,w,h,speed:q.speed*rand(.92,1.2),type:t});q.spawn=Math.max(.38,.92-q.score/900)+Math.random()*.35}q.obs.forEach(o=>o.y+=o.speed*dt);q.obs=q.obs.filter(o=>o.y<H+80);for(const o of q.obs){if(q.px-16<o.x+o.w-5&&q.px+16>o.x+5&&H-105<o.y+o.h-4&&H-57>o.y+4){end();break}}setScore(Math.floor(q.score))}ctx.clearRect(0,0,W,H);ctx.fillStyle='#17201d';ctx.fillRect(0,0,W,H);ctx.fillStyle='#2e3436';ctx.fillRect(34,0,W-68,H);ctx.fillStyle='#252a2c';ctx.fillRect(45,0,W-90,H);ctx.fillStyle='#6b6f6d';ctx.fillRect(0,0,34,H);ctx.fillRect(W-34,0,34,H);ctx.fillStyle='#e8d27a';const off=(now/1000*q.speed)%80;for(let y=-80+off;y<H;y+=80)ctx.fillRect(W/2-3,y,6,38);for(const o of q.obs){if(o.type==='car'){ctx.fillStyle='#c43d3d';rr(ctx,o.x,o.y,o.w,o.h,9);ctx.fill();ctx.fillStyle='#1d2930';rr(ctx,o.x+8,o.y+15,o.w-16,28,6);ctx.fill();ctx.fillStyle='#e9f5ff';ctx.fillRect(o.x+8,o.y+19,o.w-16,8)}else if(o.type==='barrier'){ctx.fillStyle='#e0e2e0';rr(ctx,o.x,o.y,o.w,o.h,5);ctx.fill();ctx.fillStyle='#d44b3e';for(let x=o.x;x<o.x+o.w;x+=20)ctx.fillRect(x,o.y,10,o.h)}else{ctx.fillStyle='#ff8a24';ctx.beginPath();ctx.moveTo(o.x+o.w/2,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.lineTo(o.x,o.y+o.h);ctx.closePath();ctx.fill()}}ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(q.px,H-54,24,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f2c49b';ctx.beginPath();ctx.arc(q.px,H-93,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1d2630';rr(ctx,q.px-11,H-83,22,27,7);ctx.fill();ctx.strokeStyle='#f2c49b';ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(q.px-8,H-60);ctx.lineTo(q.px-13,H-47);ctx.moveTo(q.px+8,H-60);ctx.lineTo(q.px+13,H-47);ctx.moveTo(q.px-10,H-76);ctx.lineTo(q.px-19,H-68);ctx.moveTo(q.px+10,H-76);ctx.lineTo(q.px+19,H-68);ctx.stroke();if(q.running)raf.current=requestAnimationFrame(draw)};draw(performance.now());if(screen==='game'){g.current.last=performance.now();raf.current=requestAnimationFrame(draw)}return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[screen,end]);
 const move=(e:React.PointerEvent)=>{const c=canvasRef.current;if(!c)return;const r=c.getBoundingClientRect();g.current.tx=Math.max(58,Math.min(W-58,(e.clientX-r.left)/r.width*W))};
 return <main className="shell"><div className="top"><b>STREET <i>ESCAPE</i></b><small>BEST {best}</small></div><div className="game" onPointerDown={move} onPointerMove={e=>{if(e.buttons)move(e)}}><canvas ref={canvasRef}/>{screen==='game'&&<div className="hud">🏆 {score}<span>← DRAG →</span></div>}{screen!=='game'&&<div className="overlay"><section><small>CITY RUNNER</small><h1>{screen==='start'?'STREET ESCAPE':'GAME OVER'}</h1><p>{screen==='start'?'RUN. DODGE. SURVIVE.':`You survived ${score} points`}</p><button onClick={start}>{screen==='start'?'START RUN':'RUN AGAIN'} →</button></section></div>}</div><p className="hint">اسحب إصبعك يمينًا ويسارًا لتجنب السيارات والحواجز.</p></main>}
